local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#FFFFFF"},
DapUIFrameName = {link = "Normal"},
DapUINormal = {link = "Normal"},
DapUINormalNC = {link = "Normal"},
DapUIValue = {link = "Normal"},
DapUIVariable = {link = "Normal"},
NormalNC = {link = "Normal"},
typstMarkupBulletList = {link = "Normal"},
typstMarkupEnumList = {link = "Normal"},
Bold = {bold = true},
CmpGhostText = {fg = "#6FC7D3"},
CmpItemKindCopilot = {fg = "#F27821"},
CmpItemKindDefault = {fg = "#D3C6AB"},
CmpItemKindText = {fg = "#363B45"},
Comment = {fg = "#7C7F7A"},
typstCommentBlock = {link = "Comment"},
typstCommentLine = {link = "Comment"},
Conceal = {fg = "#E5C338"},
typstCodeConditional = {link = "Conditional"},
typstHashtagConditional = {link = "Conditional"},
Constant = {fg = "#D3C6AB"},
Boolean = {link = "Constant"},
Character = {link = "Constant"},
Number = {link = "Constant"},
String = {link = "Constant"},
typstCodeConstant = {link = "Constant"},
typstHashtagConstant = {link = "Constant"},
typstMarkupDash = {link = "Constant"},
typstMarkupEllipsis = {link = "Constant"},
typstMarkupShy = {link = "Constant"},
typstMarkupTermList = {link = "Constant"},
Cursor = {},
CursorIM = {},
CursorLine = {bg = "#0D0D0D"},
ColorColumn = {link = "CursorLine"},
CursorColumn = {link = "CursorLine"},
CursorLineNr = {fg = "#F2AB26", bold = true},
DapUIBreakpointsCurrentLine = {},
DapUICurrentFrameName = {link = "DapUIBreakpointsCurrentLine"},
DapUIBreakpointsDisabledLine = {},
DapUIBreakpointsInfo = {},
DapUIBreakpointsPath = {},
DapUIDecoration = {},
DapUIFloatBorder = {},
DapUILineNumber = {fg = "#8AD2DB", bg = "#17444A"},
DapUIBreakpointsLine = {link = "DapUILineNumber"},
DapUIModifiedValue = {},
DapUIPlayPause = {},
DapUIPlayPauseNC = {},
DapUIRestart = {},
DapUIRestartNC = {},
DapUIScope = {},
DapUISource = {},
DapUIStepBack = {},
DapUIStepBackNC = {},
DapUIStepInto = {},
DapUIStepIntoNC = {},
DapUIStepOut = {},
DapUIStepOutNC = {},
DapUIStepOver = {},
DapUIStepOverNC = {},
DapUIStop = {},
DapUIStopNC = {},
DapUIStoppedThread = {},
DapUIThread = {},
DapUIType = {},
DapUIUnavailable = {},
DapUIUnavailableNC = {},
DapUIWatchesEmpty = {},
DapUIWatchesError = {},
DapUIWatchesValue = {},
DapUIWinSelect = {},
Delimiter = {fg = "#58606F"},
DiffAdd = {bg = "#2C471F"},
GitSignsAdd = {link = "DiffAdd"},
GitSignsAddLn = {link = "DiffAdd"},
GitSignsAddPreview = {link = "DiffAdd"},
diffAdded = {link = "DiffAdd"},
DiffChange = {bg = "#523D14"},
GitSignsChange = {link = "DiffChange"},
GitSignsChangeLn = {link = "DiffChange"},
diffChanged = {link = "DiffChange"},
DiffDelete = {fg = "#592626", bg = "#471F1F"},
GitSignsDelete = {link = "DiffDelete"},
GitSignsDeletePreview = {link = "DiffDelete"},
GitSignsDeleteVirtLn = {link = "DiffDelete"},
WildMenu = {link = "DiffDelete"},
DiffText = {bg = "#936E25"},
Directory = {},
EndOfBuffer = {},
DapUIEndofBuffer = {link = "EndOfBuffer"},
Error = {fg = "#FFFFFF", bg = "#B30000"},
ErrorMsg = {link = "Error"},
typstHashtagControlFlowError = {link = "Error"},
Floaterm = {bg = "#1B1D22"},
Function = {fg = "#D0AB1B", bold = true},
typstCodeFunction = {link = "Function"},
typstHashtagFunction = {link = "Function"},
GitSignsAddNr = {link = "GitSignsAdd"},
GitSignsUntracked = {link = "GitSignsAdd"},
GitSignsAddLnInline = {link = "GitSignsAddInline"},
GitSignsUntrackedLn = {link = "GitSignsAddLn"},
GitSignsUntrackedNr = {link = "GitSignsAddNr"},
GitSignsChangeNr = {link = "GitSignsChange"},
GitSignsChangedelete = {link = "GitSignsChange"},
GitSignsChangeLnInline = {link = "GitSignsChangeInline"},
GitSignsChangedeleteLn = {link = "GitSignsChangeLn"},
GitSignsChangedeleteNr = {link = "GitSignsChangeNr"},
GitSignsDeleteNr = {link = "GitSignsDelete"},
GitSignsTopdelete = {link = "GitSignsDelete"},
GitSignsDeleteLnInline = {link = "GitSignsDeleteInline"},
GitSignsDeleteVirtLnInLine = {link = "GitSignsDeleteLnInline"},
GitSignsTopdeleteNr = {link = "GitSignsDeleteNr"},
GitSignsVirtLnum = {link = "GitSignsDeleteVirtLn"},
Identifier = {fg = "#EACF61"},
typstCodeFieldAccess = {link = "Identifier"},
typstCodeIdentifier = {link = "Identifier"},
typstHashtagFieldAccess = {link = "Identifier"},
typstHashtagIdentifier = {link = "Identifier"},
IncSearch = {fg = "#000000", bg = "#7C8598", bold = true, underline = true},
Italic = {italic = true},
Keyword = {fg = "#BFC1BE", italic = true},
Conditional = {link = "Keyword"},
Exception = {link = "Keyword"},
Label = {link = "Keyword"},
Repeat = {link = "Keyword"},
typstCodeKeyword = {link = "Keyword"},
typstHashtagKeyword = {link = "Keyword"},
LineNr = {fg = "#5B4D34"},
LspDiagnosticsFloatingError = {bg = "#471F1F"},
LspDiagnosticsFloatingHint = {bg = "#2C471F"},
LspDiagnosticsFloatingInformation = {bg = "#1F3347"},
LspDiagnosticsFloatingWarning = {bg = "#523D14"},
LspDiagnosticsUnderlineError = {fg = "#813737", underline = true},
LspDiagnosticsUnderlineHint = {fg = "#508137", underline = true},
LspDiagnosticsUnderlineInformation = {fg = "#375C81", underline = true},
LspDiagnosticsUnderlineWarning = {fg = "#936E25", underline = true},
LspDiagnosticsVirtualTextError = {fg = "#471F1F"},
LspDiagnosticsVirtualTextHint = {fg = "#2C471F"},
LspDiagnosticsVirtualTextInformation = {fg = "#1F3347"},
LspDiagnosticsVirtualTextWarning = {fg = "#523D14"},
LspReferenceRead = {fg = "#C27070"},
LspReferenceText = {fg = "#C27070"},
LspReferenceWrite = {fg = "#C27070"},
typstMarkupRawBlock = {link = "Macro"},
typstMarkupRawInline = {link = "Macro"},
MatchParen = {fg = "#6FC7D3"},
ModeMsg = {fg = "#5B4D34"},
MoreMsg = {},
MsgSeparator = {},
Noise = {fg = "#A9B0BC"},
MsgArea = {link = "Noise"},
typstCodeBrace = {link = "Noise"},
typstCodeBracket = {link = "Noise"},
typstCodeDollar = {link = "Noise"},
typstCodeParen = {link = "Noise"},
typstHashtagBrace = {link = "Noise"},
typstHashtagBracket = {link = "Noise"},
typstHashtagControlFlow = {link = "Noise"},
typstHashtagDollar = {link = "Noise"},
typstHashtagParen = {link = "Noise"},
typstMarkupBoldDelimiter = {link = "Noise"},
typstMarkupDollar = {link = "Noise"},
typstMarkupItalicDelimiter = {link = "Noise"},
typstMarkupLinebreak = {link = "Noise"},
GitSignsCurrentLineBlame = {link = "NonText"},
NormalFloat = {fg = "#FFFFFF", bg = "#1B1D22"},
DapUIFloatNormal = {link = "NormalFloat"},
FloatBorder = {link = "NormalFloat"},
FloatermBorder = {link = "NormalFloat"},
Float = {link = "Number"},
typstCodeNumberAngle = {link = "Number"},
typstCodeNumberFloat = {link = "Number"},
typstCodeNumberFraction = {link = "Number"},
typstCodeNumberInteger = {link = "Number"},
typstCodeNumberLength = {link = "Number"},
typstCodeNumberRatio = {link = "Number"},
Operator = {fg = "#7C7F7A"},
Pmenu = {fg = "#5B4D34", bg = "#1B1D22"},
TelescopeNormal = {link = "Pmenu"},
WhichKeySeperator = {link = "Pmenu"},
PmenuSbar = {bg = "#1B1D22"},
PmenuSel = {fg = "#F2AB26", bg = "#1B1D22"},
TelescopeSelection = {link = "PmenuSel"},
WhichKeyFloating = {link = "PmenuSel"},
PmenuThumb = {bg = "#5B4D34"},
PreProc = {fg = "#D0A453"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
Question = {},
QuickFixLine = {},
typstCodeRepeat = {link = "Repeat"},
typstHashtagRepeat = {link = "Repeat"},
ScrollView = {bg = "#5B4D34"},
Search = {fg = "#000000", bg = "#7C8598"},
SignColumn = {},
Special = {fg = "#EAE4D7"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
SpecialKey = {fg = "#E5C338"},
SpellBad = {bg = "#59364D"},
SpellCap = {},
SpellLocal = {},
SpellRare = {},
Statement = {fg = "#FFFFFF", bold = true, italic = true},
typstCodeStatement = {link = "Statement"},
typstHashtagStatementWord = {link = "Statement"},
StatusLine = {fg = "#F2AB26", bg = "#363B45", bold = true},
StatusLineNC = {fg = "#5B4D34", bg = "#1B1D22"},
StorageClass = {fg = "#B9A583"},
typstCodeString = {link = "String"},
Structure = {fg = "#A3895C"},
Substitute = {},
Tabline = {fg = "#5B4D34", bg = "#1B1D22"},
TablineSel = {fg = "#F2AB26", bg = "#363B45", bold = true},
TelescopeBorder = {fg = "#1B1D22", bg = "#1B1D22"},
TelescopeMatching = {fg = "#1B1D22", bg = "#F2AB26", bold = true},
TelescopeNormalBorder = {link = "TelescopeNormal"},
TelescopePreviewMessage = {fg = "#090A0B"},
TelescopePreviewNormal = {fg = "#B3B3B3", bg = "#0D0F11"},
TelescopePreviewBorder = {link = "TelescopePreviewNormal"},
TelescopePreviewTitle = {fg = "#040506", bg = "#0B0C0E", italic = true},
TelescopePromptBorder = {fg = "#E5C338", bg = "#E5C338"},
TelescopePromptCounter = {fg = "#4D3F0A"},
TelescopePromptNormal = {fg = "#000000", bg = "#E5C338", bold = true},
TelescopePromptPrefix = {fg = "#4D3F0A", bold = true},
TelescopePromptTitle = {fg = "#4D3F0A", bg = "#EACF61", italic = true},
TelescopeSelectionCaret = {fg = "#9BA3B0", bg = "#1B1D22", bold = true},
TelescopeTitle = {fg = "#B5BAC5", bg = "#434A56", italic = true},
TermCursor = {fg = "#000000", bg = "#FFFFFF"},
GitSignsAddInline = {link = "TermCursor"},
GitSignsChangeInline = {link = "TermCursor"},
GitSignsDeleteInline = {link = "TermCursor"},
TermCursorNC = {bg = "#999999"},
Title = {fg = "#E5C338", bold = true},
typstMarkupHeading = {link = "Title"},
Todo = {fg = "#A97095"},
typstCommentTodo = {link = "Todo"},
Type = {fg = "#B9A583"},
Typedef = {fg = "#A3895C", bold = true},
URI = {fg = "#4D7FB3", underline = true},
typstMarkupURL = {link = "URI"},
Underlined = {underline = true},
VertSplit = {fg = "#5B4D34"},
TablineFill = {link = "VertSplit"},
Visual = {fg = "#000000", bg = "#E5C338"},
VisualNOS = {},
WarningMsg = {fg = "#FFFFFF", bg = "#7A5C1F"},
WhichKey = {bold = true},
WhichKeyDesc = {fg = "#F2AB26", bg = "#1B1D22", italic = true},
WhichKeyGroup = {fg = "#5B4D34", bg = "#1B1D22", italic = true},
Whitespace = {fg = "#363B45"},
FoldColumn = {link = "Whitespace"},
Folded = {link = "Whitespace"},
Ignore = {link = "Whitespace"},
NonText = {link = "Whitespace"},
typstMarkupNonbreakingSpace = {link = "Whitespace"},
diffRemoved = {fg = "#C67B7B", bg = "#471F1F"},
fugitiveStagedModifier = {fg = "#508137"},
fugitiveUnstagedModifier = {fg = "#C89632"},
fugitiveUntrackedModifier = {fg = "#813737"},
lCursor = {},
typstCodeFunctionArgument = {},
typstCodeStatementWord = {fg = "#FFFFFF", bold = true, italic = true},
typstHashtagKeywords = {},
typstHashtagStatement = {},
typstMarkupBold = {bold = true},
typstMarkupItalic = {italic = true},
typstMarkupReference = {fg = "#A99066"},
typstMarkupLabel = {link = "typstMarkupReference"},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='kurzzug'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
