local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#FFFFFF"},
NormalNC = {link = "Normal"},
Bold = {bold = true},
Comment = {fg = "#7C7F7A"},
Conceal = {fg = "#E5C338"},
Constant = {fg = "#D3C6AB"},
Boolean = {link = "Constant"},
Character = {link = "Constant"},
Number = {link = "Constant"},
String = {link = "Constant"},
Cursor = {},
CursorIM = {},
CursorLine = {bg = "#0D0D0D"},
ColorColumn = {link = "CursorLine"},
CursorColumn = {link = "CursorLine"},
CursorLineNr = {fg = "#F2AB26", bold = true},
Delimiter = {fg = "#58606F"},
DiffAdd = {bg = "#2C471F"},
DiffChange = {bg = "#523D14"},
DiffDelete = {fg = "#592626", bg = "#471F1F"},
WildMenu = {link = "DiffDelete"},
DiffText = {bg = "#936E25"},
Directory = {},
EndOfBuffer = {},
Error = {fg = "#FFFFFF", bg = "#B30000"},
ErrorMsg = {link = "Error"},
Function = {fg = "#D0AB1B", bold = true},
Identifier = {fg = "#EACF61"},
IncSearch = {fg = "#000000", bg = "#7C8598", bold = true, underline = true},
Italic = {italic = true},
Keyword = {fg = "#BFC1BE", italic = true},
Conditional = {link = "Keyword"},
Exception = {link = "Keyword"},
Label = {link = "Keyword"},
Repeat = {link = "Keyword"},
LineNr = {fg = "#5B4D34"},
LspDiagnosticsFloatingError = {bg = "#471F1F"},
LspDiagnosticsFloatingHint = {bg = "#2C471F"},
LspDiagnosticsFloatingInformation = {bg = "#1F3347"},
LspDiagnosticsFloatingWarning = {bg = "#523D14"},
LspDiagnosticsUnderlineError = {fg = "#813737", underline = true},
LspDiagnosticsUnderlineHint = {fg = "#508137", underline = true},
LspDiagnosticsUnderlineInformation = {fg = "#375C81", underline = true},
LspDiagnosticsUnderlineWarning = {fg = "#936E25", underline = true},
LspDiagnosticsVirtualTextError = {fg = "#471F1F"},
LspDiagnosticsVirtualTextHint = {fg = "#2C471F"},
LspDiagnosticsVirtualTextInformation = {fg = "#1F3347"},
LspDiagnosticsVirtualTextWarning = {fg = "#523D14"},
LspReferenceRead = {fg = "#C27070"},
LspReferenceText = {fg = "#C27070"},
LspReferenceWrite = {fg = "#C27070"},
MatchParen = {fg = "#6FC7D3"},
ModeMsg = {fg = "#5B4D34"},
MoreMsg = {},
MsgSeparator = {},
Noise = {fg = "#A9B0BC"},
MsgArea = {link = "Noise"},
NormalFloat = {fg = "#FFFFFF", bg = "#1B1D22"},
FloatBorder = {link = "NormalFloat"},
Float = {link = "Number"},
Operator = {fg = "#7C7F7A"},
Pmenu = {fg = "#5B4D34", bg = "#1B1D22"},
PmenuSbar = {bg = "#1B1D22"},
PmenuSel = {fg = "#F2AB26", bg = "#1B1D22"},
PmenuThumb = {bg = "#5B4D34"},
PreProc = {fg = "#D0A453"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
Question = {},
QuickFixLine = {},
Search = {fg = "#000000", bg = "#7C8598"},
SignColumn = {},
Special = {fg = "#EAE4D7"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
SpecialKey = {fg = "#E5C338"},
SpellBad = {bg = "#59364D"},
SpellCap = {},
SpellLocal = {},
SpellRare = {},
Statement = {fg = "#FFFFFF", bold = true, italic = true},
StatusLine = {fg = "#F2AB26", bg = "#363B45", bold = true},
StatusLineNC = {fg = "#5B4D34", bg = "#1B1D22"},
StorageClass = {fg = "#B9A583"},
Structure = {fg = "#A3895C"},
Substitute = {},
Tabline = {fg = "#5B4D34", bg = "#1B1D22"},
TablineSel = {fg = "#F2AB26", bg = "#363B45", bold = true},
TermCursor = {fg = "#000000", bg = "#FFFFFF"},
TermCursorNC = {bg = "#999999"},
Title = {fg = "#E5C338", bold = true},
Todo = {fg = "#A97095"},
Type = {fg = "#B9A583"},
Typedef = {fg = "#A3895C", bold = true},
URI = {fg = "#4D7FB3", underline = true},
Underlined = {underline = true},
VertSplit = {fg = "#5B4D34"},
TablineFill = {link = "VertSplit"},
Visual = {fg = "#000000", bg = "#E5C338"},
VisualNOS = {},
WarningMsg = {fg = "#FFFFFF", bg = "#7A5C1F"},
Whitespace = {fg = "#363B45"},
FoldColumn = {link = "Whitespace"},
Folded = {link = "Whitespace"},
Ignore = {link = "Whitespace"},
NonText = {link = "Whitespace"},
lCursor = {},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='kurzzug'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
